=== nathanmerrill/TDGGP/games/game.xsd
<?xml version="1.0"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:group name="action">
        <xs:choice>
            <xs:element name="perform">
                <xs:complexType>
                    <xs:attribute type="xs:string" name="action" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="select">
                <xs:complexType>
                    <xs:sequence minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="filter">
                            <xs:complexType>
                                <xs:attribute type="xs:string" name="exists" use="optional"/>
                                <xs:attribute type="xs:string" name="test" use="optional"/>
                                <xs:attribute type="xs:positiveInteger" name="random" use="optional"/>
                                <xs:attribute type="xs:boolean" name="out" use="optional"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute type="xs:string" name="from" use="required"/>
                    <xs:attribute type="xs:string" name="label" use="optional"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="end-game">
                <xs:complexType>
                    <xs:attribute type="xs:string" name="winners" use="required" />
                </xs:complexType>
            </xs:element>
            <xs:element name="if">
                <xs:complexType>
                    <xs:all>
                        <xs:element name="true" minOccurs="0">
                            <xs:complexType>
                                <xs:choice maxOccurs="unbounded">
                                    <xs:group ref="action" />
                                </xs:choice>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="false" minOccurs="0">
                            <xs:complexType>
                                <xs:choice maxOccurs="unbounded">
                                    <xs:group ref="action" />
                                </xs:choice>
                            </xs:complexType>
                        </xs:element>
                    </xs:all>
                    <xs:attribute type="xs:string" name="test" use="optional"/>
                    <xs:attribute type="xs:string" name="exists" use="optional"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="assign-attribute">
                <xs:complexType>
                    <xs:attribute type="xs:string" name="attribute" use="required"/>
                    <xs:attribute type="xs:string" name="value" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="give-turn">
                <xs:complexType>
                    <xs:attribute type="xs:string" name="to" use="required"/>
                    <xs:attribute type="xs:string" name="turn" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="shuffle-collection">
                <xs:complexType>
                    <xs:attribute type="xs:string" name="collection" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="repeat">
                <xs:complexType>
                    <xs:choice maxOccurs="unbounded" minOccurs="1">
                        <xs:group ref="action" />
                    </xs:choice>
                    <xs:attribute type="xs:string" name="test" use="optional" />
                    <xs:attribute type="xs:string" name="exists" use="optional" />
                    <xs:attribute type="xs:string" name="count" use="optional" />
                    <xs:attribute type="xs:string" name="over" use="optional" />
                    <xs:attribute type="xs:string" name="label" use="optional"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="move-pieces">
                <xs:complexType>
                    <xs:attribute type="xs:string" name="pieces" use="required"/>
                    <xs:attribute type="xs:string" name="to" use="required"/>
                    <xs:attribute type="xs:boolean" name="copy" use="optional"/>
                    <xs:attribute type="xs:string" name="count" use="optional" />
                </xs:complexType>
            </xs:element>
            <xs:element name="player-choice">
                <xs:complexType mixed="true">
                    <xs:sequence>
                        <xs:element name="option" maxOccurs="unbounded" minOccurs="2">
                            <xs:complexType>
                                <xs:choice maxOccurs="unbounded" minOccurs="0">
                                    <xs:group ref="action" />
                                </xs:choice>
                                <xs:attribute type="xs:string" name="value" use="required"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute type="xs:string" name="player" use="optional"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="player-select">
                <xs:complexType>
                    <xs:sequence minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="filter">
                            <xs:complexType>
                                <xs:attribute type="xs:string" name="exists" use="optional"/>
                                <xs:attribute type="xs:string" name="test" use="optional"/>
                                <xs:attribute type="xs:positiveInteger" name="random" use="optional"/>
                                <xs:attribute type="xs:boolean" name="out" use="optional"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute type="xs:string" name="from" use="required"/>
                    <xs:attribute type="xs:nonNegativeInteger" name="max" use="optional"/>
                    <xs:attribute type="xs:nonNegativeInteger" name="min" use="optional"/>
                    <xs:attribute type="xs:string" name="label" use="optional"/>
                </xs:complexType>
            </xs:element>
        </xs:choice>
    </xs:group>
    <xs:element name="game">
        <xs:complexType>
            <xs:all>
                <xs:element name="pieces">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="piece" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="attribute" maxOccurs="unbounded" minOccurs="0">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="name" type="xs:string" use="required"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="relation" maxOccurs="unbounded" minOccurs="0">
                                            <xs:complexType>
                                                <xs:attribute type="xs:string" name="name" use="required"/>
                                                <xs:attribute type="xs:string" name="to" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute type="xs:string" name="id" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="turns">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="turn" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:attribute type="xs:string" name="id" use="required"/>
                                    <xs:attribute type="xs:string" name="action" use="required"/>
                                    <xs:attribute type="xs:boolean" name="initial" use="optional" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="actions">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="action" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:choice maxOccurs="unbounded" minOccurs="0">
                                        <xs:element name="parameter">
                                            <xs:complexType>
                                                <xs:attribute type="xs:string" name="name" use="required"/>
                                                <xs:attribute type="xs:string" name="default" use="optional"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:group ref="action" />
                                    </xs:choice>
                                    <xs:attribute type="xs:string" name="id" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="collections">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="collection" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="attribute" maxOccurs="unbounded" minOccurs="0">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="name" type="xs:string" use="required"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="visibility" maxOccurs="unbounded" minOccurs="0">
                                            <xs:complexType>
                                                <xs:attribute type="xs:string" name="item" use="required"/>
                                                <xs:attribute type="xs:string" name="to" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute type="xs:string" name="id" use="required"/>
                                    <xs:attribute type="xs:string" name="scope" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
            <xs:attribute type="xs:positiveInteger" name="min_players"/>
            <xs:attribute type="xs:nonNegativeInteger" name="max_players"/>
            <xs:attribute type="xs:string" name="name"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== nathanmerrill/TDGGP/games/dominion.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<game xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      min_players="2"
      max_players="4"
      name="dominion"
      xsi:noNamespaceSchemaLocation="game.xsd">
    <pieces>
        <piece id="card_copper">
            <attribute name="value">1</attribute>
            <attribute name="cost">0</attribute>
            <attribute name="base">true</attribute>
            <attribute name="treasure">true</attribute>
        </piece>
        <piece id="card_silver">
            <attribute name="value">2</attribute>
            <attribute name="cost">3</attribute>
            <attribute name="base">true</attribute>
            <attribute name="treasure">true</attribute>
        </piece>
        <piece id="card_gold">
            <attribute name="value">3</attribute>
            <attribute name="cost">6</attribute>
            <attribute name="base">true</attribute>
            <attribute name="treasure">true</attribute>
        </piece>
        <piece id="card_curse">
            <attribute name="value">0</attribute>
            <attribute name="cost">0</attribute>
            <attribute name="points">-1</attribute>
            <attribute name="base">true</attribute>
        </piece>
        <piece id="card_estate">
            <attribute name="value">0</attribute>
            <attribute name="cost">2</attribute>
            <attribute name="points">1</attribute>
            <attribute name="base">true</attribute>
            <attribute name="victory">true</attribute>
        </piece>
        <piece id="card_duchy">
            <attribute name="value">0</attribute>
            <attribute name="cost">5</attribute>
            <attribute name="points">3</attribute>
            <attribute name="base">true</attribute>
            <attribute name="victory">true</attribute>
        </piece>
        <piece id="card_province">
            <attribute name="value">0</attribute>
            <attribute name="cost">8</attribute>
            <attribute name="points">6</attribute>
            <attribute name="base">true</attribute>
            <attribute name="victory">true</attribute>
        </piece>
        <piece id="card_gardens">
            <attribute name="value">0</attribute>
            <attribute name="cost">4</attribute>
            <attribute name="points">garden</attribute>
            <attribute name="victory">true</attribute>
        </piece>
        <piece id="card_cellar">
            <attribute name="value">0</attribute>
            <attribute name="cost">2</attribute>
            <relation name="action" to="action_card_cellar"/>
        </piece>
        <piece id="card_chapel">
            <attribute name="value">0</attribute>
            <attribute name="cost">2</attribute>
            <relation name="action" to="action_card_chapel"/>
        </piece>
        <piece id="card_moat">
            <attribute name="value">0</attribute>
            <attribute name="cost">2</attribute>
            <relation name="action" to="action_card_moat"/>
            <relation name="reaction" to="reaction_card_moat"/>
        </piece>
        <piece id="card_chancellor">
            <attribute name="value">0</attribute>
            <attribute name="cost">3</attribute>
            <relation name="action" to="action_card_chancellor"/>
        </piece>
        <piece id="card_village">
            <attribute name="value">0</attribute>
            <attribute name="cost">3</attribute>
            <relation name="action" to="action_card_village"/>
        </piece>
        <piece id="card_woodcutter">
            <attribute name="value">0</attribute>
            <attribute name="cost">3</attribute>
            <relation name="action" to="action_card_woodcutter"/>
        </piece>
        <piece id="card_workshop">
            <attribute name="value">0</attribute>
            <attribute name="cost">3</attribute>
            <relation name="action" to="action_card_workshop"/>
        </piece>
        <piece id="card_bureaucrat">
            <attribute name="value">0</attribute>
            <attribute name="cost">4</attribute>
            <attribute name="attack">true</attribute>
            <relation name="action" to="action_card_bureaucrat"/>
        </piece>
        <piece id="card_feast">
            <attribute name="value">0</attribute>
            <attribute name="cost">4</attribute>
            <relation name="action" to="action_card_feast"/>
        </piece>
        <piece id="card_militia">
            <attribute name="value">0</attribute>
            <attribute name="cost">4</attribute>
            <attribute name="attack">true</attribute>
            <relation name="action" to="action_card_militia"/>
        </piece>
        <piece id="card_moneylender">
            <attribute name="value">0</attribute>
            <attribute name="cost">4</attribute>
            <relation name="action" to="action_card_moneylender"/>
        </piece>
        <piece id="card_remodel">
            <attribute name="value">0</attribute>
            <attribute name="cost">4</attribute>
            <relation name="action" to="action_card_remodel"/>
        </piece>
        <piece id="card_smithy">
            <attribute name="value">0</attribute>
            <attribute name="cost">4</attribute>
            <relation name="action" to="action_card_smithy"/>
        </piece>
        <piece id="card_spy">
            <attribute name="value">0</attribute>
            <attribute name="cost">4</attribute>
            <relation name="action" to="action_card_spy"/>
        </piece>
        <piece id="card_thief">
            <attribute name="value">0</attribute>
            <attribute name="cost">4</attribute>
            <relation name="action" to="action_card_thief"/>
        </piece>
        <piece id="card_throne_room">
            <attribute name="value">0</attribute>
            <attribute name="cost">4</attribute>
            <relation name="action" to="action_card_throne_room"/>
        </piece>
        <piece id="card_council_room">
            <attribute name="value">0</attribute>
            <attribute name="cost">5</attribute>
            <relation name="action" to="action_card_council_room"/>
        </piece>
        <piece id="card_festival">
            <attribute name="value">0</attribute>
            <attribute name="cost">5</attribute>
            <relation name="action" to="action_card_festival"/>
        </piece>
        <piece id="card_laboratory">
            <attribute name="value">0</attribute>
            <attribute name="cost">5</attribute>
            <relation name="action" to="action_card_laboratory"/>
        </piece>
        <piece id="card_library">
            <attribute name="value">0</attribute>
            <attribute name="cost">5</attribute>
            <relation name="action" to="action_card_library"/>
        </piece>
        <piece id="card_market">
            <attribute name="value">0</attribute>
            <attribute name="cost">5</attribute>
            <relation name="action" to="action_card_market"/>
        </piece>
        <piece id="card_mine">
            <attribute name="value">0</attribute>
            <attribute name="cost">5</attribute>
            <relation name="action" to="action_card_mine"/>
        </piece>
        <piece id="card_witch">
            <attribute name="value">0</attribute>
            <attribute name="cost">5</attribute>
            <relation name="action" to="action_card_witch"/>
        </piece>
        <piece id="card_adventurer">
            <attribute name="value">0</attribute>
            <attribute name="cost">6</attribute>
            <relation name="action" to="action_card_adventurer"/>
        </piece>
    </pieces>
    <turns>
        <turn id="start_turn" initial="true" action="action_start"/>
        <turn id="game_loop" action="action_game_loop"/>
        <turn id="council_room" action="action_council_room"/>
        <turn id="reaction" action="action_reaction"/>
        <turn id="bureaucrat_attack" action="action_bureaucrat_attack"/>
        <turn id="militia_attack" action="action_militia_attack"/>
        <turn id="spy_attack" action="action_spy_attack"/>
        <turn id="thief_attack" action="action_thief_attack"/>
        <turn id="witch_attack" action="action_witch_attack"/>
        <turn id="clean_up" action="action_clean_up" />
    </turns>
    <actions>
        <action id="play_card">
            <player-select from="player:hand:pieces[@action]" max="1" label="selectedCard" />
            <if exists="$selectedCard">
                <true>
                    <assign-attribute attribute="current_turn@actions" value="current_turn@actions - 1"/>
                    <move-pieces pieces="$selectedCard" to="player:played" />
                    <perform action="$selectedCard@action"/>
                    <if test="current_turn@actions > 0">
                        <true>
                            <perform action="action::play_card" />
                        </true>
                    </if>
                </true>
            </if>
        </action>
        <action id="buy_card">
            <select from="current_turn@treasure" label="max_cost" />
            <remove label="purchased" />
            <perform action="action::card_from_reserve" />
            <if exists="$purchased">
                <true>
                    <assign-attribute attribute="current_turn@buys" value="current_turn@buys - 1" />
                    <assign-attribute attribute="current_turn@treasure" value="current_turn@treasure - first(player:discard:pieces)@cost" />
                    <if test="current_turn@buys > 0">
                        <true>
                            <perform action="action::buy_card" />
                        </true>
                    </if>
                </true>
            </if>
        </action>
        <action id="action_find_treasure">
